from __future__ import annotations

from threading import RLock
from typing import Dict, List, Optional

from .knowledge import chunk_document
from .models import (
    AgentRun,
    AgentStep,
    Approval,
    AuditLog,
    Document,
    DocumentChunk,
    Ticket,
    ToolCall,
)
from .time_utils import utc_now


class NotFoundError(KeyError):
    pass


class InMemoryStore:
    def __init__(self, seed: bool = True) -> None:
        self._lock = RLock()
        self.tickets: Dict[str, Ticket] = {}
        self.documents: Dict[str, Document] = {}
        self.chunks: Dict[str, DocumentChunk] = {}
        self.runs: Dict[str, AgentRun] = {}
        self.steps: Dict[str, AgentStep] = {}
        self.tool_calls: Dict[str, ToolCall] = {}
        self.approvals: Dict[str, Approval] = {}
        self.audit_logs: Dict[str, AuditLog] = {}

        if seed:
            self.seed()

    def seed(self) -> None:
        if self.documents:
            return

        self.add_document(
            Document(
                tenant_id="acme",
                title="API Authentication Runbook",
                source_type="api_doc",
                uri="kb://api/authentication-runbook",
                content=(
                    "401 Unauthorized responses are usually caused by a missing Authorization header, "
                    "an expired access token, invalid API key, or insufficient OAuth scope.\n\n"
                    "Support should ask for request_id and timestamp, check auth service logs, verify "
                    "the token expiration time, and confirm that the customer is using Bearer token syntax.\n\n"
                    "Do not request raw secrets. Ask the customer to rotate credentials if an API key may be exposed."
                ),
            )
        )
        self.add_document(
            Document(
                tenant_id="acme",
                title="Historical Ticket: Expired API Token",
                source_type="historical_ticket",
                uri="ticket://hist-1042",
                content=(
                    "A customer reported API calls returning 401 after a deployment. The root cause was an "
                    "expired service account token. The support reply included steps to create a new token, "
                    "validate scopes, and retry the request with the same request_id."
                ),
            )
        )
        self.add_document(
            Document(
                tenant_id="acme",
                title="Support Escalation Policy",
                source_type="policy",
                uri="kb://policy/escalation",
                content=(
                    "Any customer-facing reply generated by an agent requires human approval before sending. "
                    "Actions that write to Jira are allowed for support engineers. Actions that modify customer "
                    "data require manual escalation and are not available to the MVP tool agent."
                ),
            )
        )
        self.add_document(
            Document(
                tenant_id="globex",
                title="Globex Private Incident",
                source_type="historical_ticket",
                uri="ticket://globex-secret",
                content="Globex-only private API outage details. This document must never appear in Acme searches.",
            )
        )

    def add_audit(self, audit: AuditLog) -> AuditLog:
        with self._lock:
            self.audit_logs[audit.id] = audit
        return audit

    def create_ticket(self, ticket: Ticket) -> Ticket:
        with self._lock:
            self.tickets[ticket.id] = ticket
        return ticket

    def list_tickets(self, tenant_id: Optional[str] = None) -> List[Ticket]:
        tickets = list(self.tickets.values())
        if tenant_id:
            tickets = [ticket for ticket in tickets if ticket.tenant_id == tenant_id]
        return sorted(tickets, key=lambda item: item.created_at, reverse=True)

    def get_ticket(self, ticket_id: str) -> Ticket:
        try:
            return self.tickets[ticket_id]
        except KeyError as exc:
            raise NotFoundError(ticket_id) from exc

    def update_ticket(self, ticket: Ticket) -> Ticket:
        ticket.updated_at = utc_now()
        with self._lock:
            self.tickets[ticket.id] = ticket
        return ticket

    def add_document(self, document: Document) -> Document:
        with self._lock:
            self.documents[document.id] = document
            for chunk in chunk_document(document):
                self.chunks[chunk.id] = chunk
        return document

    def list_documents(self, tenant_id: Optional[str] = None) -> List[Document]:
        documents = list(self.documents.values())
        if tenant_id:
            documents = [document for document in documents if document.tenant_id == tenant_id]
        return sorted(documents, key=lambda item: item.created_at, reverse=True)

    def list_chunks(self) -> List[DocumentChunk]:
        return list(self.chunks.values())

    def create_run(self, run: AgentRun) -> AgentRun:
        with self._lock:
            self.runs[run.id] = run
            ticket = self.get_ticket(run.ticket_id)
            ticket.run_ids.append(run.id)
            ticket.status = "running"
            self.update_ticket(ticket)
        return run

    def get_run(self, run_id: str) -> AgentRun:
        try:
            return self.runs[run_id]
        except KeyError as exc:
            raise NotFoundError(run_id) from exc

    def update_run(self, run: AgentRun) -> AgentRun:
        run.updated_at = utc_now()
        with self._lock:
            self.runs[run.id] = run
        return run

    def add_step(self, step: AgentStep) -> AgentStep:
        with self._lock:
            self.steps[step.id] = step
            run = self.get_run(step.run_id)
            run.step_ids.append(step.id)
            run.current_node = step.name
            self.update_run(run)
        return step

    def get_steps_for_run(self, run_id: str) -> List[AgentStep]:
        run = self.get_run(run_id)
        return [self.steps[step_id] for step_id in run.step_ids]

    def add_tool_call(self, tool_call: ToolCall) -> ToolCall:
        with self._lock:
            self.tool_calls[tool_call.id] = tool_call
            run = self.get_run(tool_call.run_id)
            run.tool_call_ids.append(tool_call.id)
            self.update_run(run)
        return tool_call

    def get_tool_calls_for_run(self, run_id: str) -> List[ToolCall]:
        run = self.get_run(run_id)
        return [self.tool_calls[call_id] for call_id in run.tool_call_ids]

    def create_approval(self, approval: Approval) -> Approval:
        with self._lock:
            self.approvals[approval.id] = approval
            run = self.get_run(approval.run_id)
            run.approval_id = approval.id
            self.update_run(run)
        return approval

    def get_approval(self, approval_id: str) -> Approval:
        try:
            return self.approvals[approval_id]
        except KeyError as exc:
            raise NotFoundError(approval_id) from exc

    def list_approvals(self, status: Optional[str] = None) -> List[Approval]:
        approvals = list(self.approvals.values())
        if status:
            approvals = [approval for approval in approvals if approval.status == status]
        return sorted(approvals, key=lambda item: item.created_at, reverse=True)

    def update_approval(self, approval: Approval) -> Approval:
        with self._lock:
            self.approvals[approval.id] = approval
        return approval

